require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


project 'DrPolaris',
        'Profread.Debug' => :debug,
        'Profread.Release' => :release,
        'Staging.Debug' => :debug,
        'Staging.Release' => :release,
        'Debug' => :debug,
        'Release' => :release

target 'DrPolaris' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'DrPolarisTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

#ENVFILES = {
#  'Debug' => '$(PODS_ROOT)/../../.env.production',
#  'Release' => '$(PODS_ROOT)/../../.env.production',
#  'Staging.Debug' => '$(PODS_ROOT)/../../.env.staging',
#  'Staging.Release' => '$(PODS_ROOT)/../../.env.staging',
#}
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      if target.name == 'react-native-config'
#        config.build_settings['ENVFILE'] = ENVFILES[config.name]
#      end
#    end
#  end
#end
